param(
	[string]$ProjectPath = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
	[string]$AdbExe,
	[string]$DeviceSerial,
	[string]$OutputPath
)

$ErrorActionPreference = "Stop"

function Resolve-AdbExe {
	param([string]$RequestedPath)

	if (-not [string]::IsNullOrWhiteSpace($RequestedPath)) {
		if (-not (Test-Path -LiteralPath $RequestedPath)) {
			throw "ADB bulunamadi: $RequestedPath"
		}
		return (Resolve-Path -LiteralPath $RequestedPath).Path
	}

	$adbCommand = Get-Command adb -ErrorAction SilentlyContinue
	if ($adbCommand) {
		return $adbCommand.Source
	}

	$defaultAdb = Join-Path $env:LOCALAPPDATA "Android\Sdk\platform-tools\adb.exe"
	if (Test-Path -LiteralPath $defaultAdb) {
		return $defaultAdb
	}

	return $null
}

function Get-AdbDeviceLines {
	param(
		[string]$ResolvedAdb,
		[string]$RequestedSerial
	)

	$deviceOutput = & $ResolvedAdb devices
	$deviceLines = @($deviceOutput | Where-Object {
		$_ -match "\S+\s+device$" -and $_ -notmatch "^List of devices attached"
	})

	if ([string]::IsNullOrWhiteSpace($RequestedSerial)) {
		return $deviceLines
	}

	return @($deviceLines | Where-Object { $_ -match "^$([regex]::Escape($RequestedSerial))\s+device$" })
}

Push-Location $ProjectPath
try {
	$resolvedAdb = Resolve-AdbExe -RequestedPath $AdbExe
	if ([string]::IsNullOrWhiteSpace($resolvedAdb)) {
		Write-Host "P11_DEVICE_OBSERVATION_SKIPPED_NO_ADB_OR_DEVICE"
		return
	}

	$deviceLines = Get-AdbDeviceLines -ResolvedAdb $resolvedAdb -RequestedSerial $DeviceSerial
	if ($deviceLines.Count -eq 0) {
		Write-Host "P11_DEVICE_OBSERVATION_SKIPPED_NO_ADB_OR_DEVICE"
		return
	}

	if ($deviceLines.Count -gt 1 -and [string]::IsNullOrWhiteSpace($DeviceSerial)) {
		throw "Birden fazla cihaz bagli. -DeviceSerial verin."
	}

	if ([string]::IsNullOrWhiteSpace($DeviceSerial)) {
		$DeviceSerial = ($deviceLines[0] -split "\s+")[0]
	}

	$logDir = Join-Path $ProjectPath "artifacts\logs"
	if (-not (Test-Path -LiteralPath $logDir)) {
		New-Item -ItemType Directory -Path $logDir -Force | Out-Null
	}

	if ([string]::IsNullOrWhiteSpace($OutputPath)) {
		$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
		$OutputPath = Join-Path $logDir ("p11_device_observation_{0}.md" -f $timestamp)
	}

	$adbPrefix = if ([string]::IsNullOrWhiteSpace($DeviceSerial)) { @() } else { @("-s", $DeviceSerial) }
	$deviceModel = (& $resolvedAdb @($adbPrefix + @("shell", "getprop", "ro.product.model"))) -join ""
	$deviceAndroid = (& $resolvedAdb @($adbPrefix + @("shell", "getprop", "ro.build.version.release"))) -join ""
	$deviceAbi = (& $resolvedAdb @($adbPrefix + @("shell", "getprop", "ro.product.cpu.abi"))) -join ""
	$memInfo = (& $resolvedAdb @($adbPrefix + @("shell", "cat", "/proc/meminfo")))
	$memTotalLine = ($memInfo | Where-Object { $_ -match "^MemTotal:" } | Select-Object -First 1)

	$reportLines = @(
		"# P11 Device Observation Report",
		"",
		"**Date:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
		"**Device serial:** $DeviceSerial",
		"**Device model:** $($deviceModel.Trim())",
		"**Android version:** $($deviceAndroid.Trim())",
		"**Primary ABI:** $($deviceAbi.Trim())",
		"**Memory:** $memTotalLine",
		"",
		"## Suggested Observation Route",
		"",
		"1. Main menu idle -> settings open/close -> exit confirm.",
		"2. Start new game -> loading -> world entry.",
		"3. Continue flow with existing save.",
		"4. Late-zone overlays where HUD and loading feel dense.",
		"",
		"## Performance Notes",
		"",
		"| Area | Observation | Risk | Follow-up |",
		"|------|-------------|------|-----------|",
		"| App launch | | | |",
		"| Main menu / settings | | | |",
		"| Start -> loading | | | |",
		"| World basic movement | | | |",
		"| Continue / load | | | |",
		"| Late-zone overlays | | | |",
		"",
		"## Worst Zones / Moments",
		"",
		"- Zone or screen:",
		"- Symptom:",
		"- Repro steps:",
		"",
		"## Candidate Backlog",
		"",
		"- [ ] Loading overlay duration or feedback tuning",
		"- [ ] Overlay animation / input latency follow-up",
		"- [ ] Zone-specific perf hotspot investigation",
		"",
		"*Generated by tools/run_p11_device_observation.ps1*"
	)

	$reportLines -join "`r`n" | Out-File -FilePath $OutputPath -Encoding utf8
	Write-Host ("P11_DEVICE_OBSERVATION_TEMPLATE_READY {0}" -f $OutputPath)
}
finally {
	Pop-Location
}