$path = "scripts/world_builder.gd"
$content = Get-Content $path -Raw

$replacements = @(
    "ARDA_TEXTURE","EDA_TEXTURE","NOTE_ICON","TALK_ICON","PORTAL_ICON","DECISION_ICON","RESOURCE_ICON","SUPPORT_ICON","WAVE_ICON","BADGE_ICON",
    "CLOUD_TEXTURE","CLOUD_TEXTURE_ALT","MOON_TEXTURE","TREE_TEXTURE","TREE_TEXTURE_ALT","HOUSE_TEXTURE","HOUSE_TEXTURE_ALT","FENCE_TEXTURE",
    "BG_FLAT_HILLS_1_TEXTURE","BG_FLAT_HILLS_2_TEXTURE","BG_FLAT_MOUNTAIN_1_TEXTURE","BG_FLAT_MOUNTAIN_2_TEXTURE","BG_FLAT_POINTY_MOUNTAINS_TEXTURE",
    "BG_FLAT_HOUSE_SHORT_TEXTURE","BG_FLAT_HOUSE_TALL_TEXTURE","BG_FLAT_TREE_03_TEXTURE","BG_FLAT_TREE_08_TEXTURE",
    "SHIP_HULL_TEXTURE","SHIP_HULL_ALT_TEXTURE","SHIP_SAIL_TEXTURE","SHIP_SMALL_SAIL_TEXTURE","SHIP_MAST_TEXTURE","SHIP_CREW_TEXTURE","SHIP_CREW_ALT_TEXTURE",
    "SHIP_FLAG_TEXTURE","SHIP_FLAG_ALT_TEXTURE","SHIP_CANNON_TEXTURE","SHIP_WOOD_TEXTURE","SHIP_NEST_TEXTURE","SMOKE_TEXTURE",
    "SKETCH_GRASS_TEXTURE","SKETCH_PATH_TEXTURE","SKETCH_PATH_CROSS_TEXTURE","SKETCH_PATH_CORNER_TEXTURE","SKETCH_PATH_END_TEXTURE",
    "SKETCH_RIVER_TEXTURE","SKETCH_RIVER_BEND_TEXTURE","SKETCH_RIVER_BRIDGE_TEXTURE",
    "SKETCH_BUILDING_DOOR_TEXTURE","SKETCH_BUILDING_WINDOW_TEXTURE","SKETCH_BUILDING_WINDOWS_TEXTURE","SKETCH_BUILDING_CENTER_TEXTURE","SKETCH_BUILDING_CORNER_TEXTURE",
    "BLOCK_BOX_TEXTURE","BLOCK_BOX_WIDE_TEXTURE","BLOCK_CART_TEXTURE","BLOCK_CART_TOP_TEXTURE",
    "BLOCK_CHARACTER_MAN_TEXTURE","BLOCK_CHARACTER_WOMAN_TEXTURE","BLOCK_CHARACTER_HORSE_TEXTURE",
    "BLOCK_FENCE_SINGLE_TEXTURE","BLOCK_FENCE_DOUBLE_TEXTURE","BLOCK_BUSH_LARGE_TEXTURE","BLOCK_BUSH_SMALL_TEXTURE",
    "BLOCK_TREE_GREEN_TEXTURE","BLOCK_TREE_ORANGE_TEXTURE","BLOCK_MARKET_STALL_BLUE_TEXTURE","BLOCK_MARKET_STALL_RED_TEXTURE",
    "BLOCK_TILE_BRIDGE_TEXTURE","BLOCK_TILE_WATER_TEXTURE","BLOCK_TILE_WOOD_TEXTURE",
    "BLOCK_BUILDING_SAND_TEXTURE","BLOCK_BUILDING_STONE_TEXTURE","BLOCK_BUILDING_FRAME_TEXTURE","BLOCK_BUILDING_ROOF_BLUE_TEXTURE","BLOCK_BUILDING_ROOF_RED_TEXTURE",
    "BLOCK_DOOR_TEXTURE","BLOCK_WINDOW_TEXTURE",
    "BOARD_CARD_BLUE_TEXTURE","BOARD_CARD_RED_TEXTURE","BOARD_CARD_GREEN_TEXTURE",
    "BOARD_CHIP_BLUE_TEXTURE","BOARD_CHIP_GREEN_TEXTURE","BOARD_CHIP_RED_TEXTURE",
    "GAME_ARROW_RIGHT_TEXTURE","GAME_ARROW_UP_TEXTURE","GAME_INFO_TEXTURE","GAME_CHECK_TEXTURE","GAME_STAR_TEXTURE","GAME_TARGET_TEXTURE",
    "SAMSUN_PAPER_TERRAIN_TEXTURE","SAMSUN_PAPER_HARBOR_TEXTURE","SAMSUN_PAPER_TELEGRAPH_TEXTURE","SAMSUN_PAPER_PEOPLE_TEXTURE","SAMSUN_PAPER_RIFT_TEXTURE",
    "SAMSUN_PAPER_MAIN_PATH_TEXTURE","SAMSUN_PAPER_CIVIC_CLUSTER_TEXTURE","SAMSUN_PAPER_WAVE_GATE_TEXTURE","SAMSUN_PAPER_DISTANT_TOWN_TEXTURE",
    "SAMSUN_PAPER_HARBOR_WATER_TEXTURE","SAMSUN_PAPER_FOREGROUND_FRAME_TEXTURE","SAMSUN_PAPER_SIDE_PATHS_TEXTURE","SAMSUN_PAPER_HARBOR_BOATS_TEXTURE",
    "SAMSUN_PAPER_SIGNAL_RIDGE_TEXTURE","SAMSUN_PAPER_SKY_LIFE_TEXTURE","SAMSUN_PAPER_DISCOVERY_PROPS_TEXTURE","SAMSUN_PAPER_COAST_DETAILS_TEXTURE",
    "SAMSUN_PAPER_ROUTE_BEADS_TEXTURE","SAMSUN_PAPER_SAFE_CLEARINGS_TEXTURE","SAMSUN_PAPER_VISTA_FLAGS_TEXTURE","SAMSUN_PAPER_SKYLINE_DEPTH_TEXTURE",
    "SAMSUN_PAPER_HARBOR_DOCK_PROPS_TEXTURE","SAMSUN_PAPER_COASTAL_LIFE_TEXTURE","SAMSUN_PAPER_SKY_SAMSUN_TEXTURE","SAMSUN_PAPER_MAP_COMPASS_TEXTURE",
    "ROOM_PAPER_WALL_TEXTURE","ROOM_PAPER_STUDY_NOOK_TEXTURE","ROOM_PAPER_FLOOR_RUG_TEXTURE","ROOM_PAPER_BOOK_PORTAL_TEXTURE",
    "ROOM_PAPER_SHELF_TEXTURE","ROOM_PAPER_BED_TEXTURE","ROOM_PAPER_WALL_STORY_TEXTURE","ROOM_PAPER_FOREGROUND_FRAME_TEXTURE","ROOM_PAPER_DESK_CLUTTER_TEXTURE",
    "OPENING_PAPER_SKY_TEXTURE","OPENING_PAPER_BENCHMARK_TEXTURE","OPENING_PAPER_TERRAIN_TEXTURE","OPENING_PAPER_PATH_TEXTURE",
    "OPENING_PAPER_VILLAGE_TEXTURE","OPENING_PAPER_BOOK_GATE_TEXTURE","OPENING_PAPER_CLUE_STATIONS_TEXTURE","OPENING_PAPER_FOREGROUND_TEXTURE"
)

$totalCount = 0
foreach ($key in $replacements) {
    $pattern = '(?<![\.\w])' + [regex]::Escape($key) + '(?![\.\w])'
    $replacement = '_textures.' + $key
    $matches = [regex]::Matches($content, $pattern)
    if ($matches.Count -gt 0) {
        $content = $content -replace $pattern, $replacement
        $totalCount += $matches.Count
    }
}

# Safety check: fix any double-prefix
$content = $content -replace '_textures\._textures\.', '_textures.'

Set-Content $path -Value $content -NoNewline
Write-Host "world_builder.gd referans guncellemesi tamamlandi - toplam $totalCount sabit"
